---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-snapshot-to-quay
spec:
  description: |-
    Tekton task to push snapshot images to quay.io using `cosign copy`. The destination for
    each image is taken from the '.spec.data.mapping' section of the release plan, in the form
    '.spec.data.mapping.components.repository', and '.spec.data.mapping.components.tags'.

    If `requireSuccessfulManagedRelease` is "true", the snapshot will only be pushed if it
    contains a status indicating that a managed pipeline has successfully completed.

    ⚠️ Note: This is a sample task that should be kept simple to serve as a good example
    of how to construct a tenant task, so any non-bugfix contributions should be moved
    to a new or existing duplicate of this task.
  params:
    - name: release
      description: Namespaced name of release - should be in format "namespace/name"
      type: string
    - name: releasePlan
      description: Namespaced name of release plan - should be in format "namespace/name"
      type: string
    - name: requireSuccessfulManagedRelease
      description: Only push if the managed release status is successful
      type: string
    - name: snapshot
      description: Namespaced name of snapshot - should be in format "namespace/name"
      type: string
    - name: skipAttestations
      description: If true, skip copying attestations and signatures
      type: string
      default: "false"
    - name: singleComponent
      description: If true, enable single component mode
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: HOME
        value: /tekton/home
    workingDir: /tekton/home
  steps:
    - name: check-release-status
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      script: |
        #!/usr/bin/env bash
        set -eux

        # Only check release status if it will be used to determine push
        if [[ "$(params.requireSuccessfulManagedRelease)" != "true" ]]; then
          echo "No release validation required, skipping check-release-status step."
          exit 0
        fi

        # check for release status and check if a managed pipeline failed
        IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
        RELEASECONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
          -o jsonpath='{.status.conditions}')
        if [ -z "$RELEASECONDITIONS" ]; then
          echo "No release conditions found for $RELEASE_NAME in namespace $RELEASE_NAMESPACE"
          exit 1
        fi
        RELEASECONDITION=$(echo "$RELEASECONDITIONS" | jq '.[] | select(.type == "ManagedPipelineProcessed")')
        RELEASESTATUS=$(jq -r '.reason' <<< "$RELEASECONDITION")
        echo "Release status: $RELEASESTATUS"

        if [[ "$RELEASESTATUS" != *"Succeeded"* ]]; then
          echo "Release did not succeed, stopping snapshot push"
          exit 1
        fi
    - name: reduce
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      env:
        - name: SNAPSHOT_REF
          value: $(params.snapshot)
        - name: SINGLE_COMPONENT
          value: $(params.singleComponent)
      script: |
        #!/usr/bin/env bash
        set -eux

        IFS='/' read -r "SNAPSHOT_NAMESPACE" "SNAPSHOT_NAME" <<< "${SNAPSHOT_REF}"
        kubectl get snapshot "$SNAPSHOT_NAME" -n "$SNAPSHOT_NAMESPACE" -o json > snapshot.json

        < snapshot.json jq '.spec' > snapshot_spec_original.json

        cp snapshot_spec_original.json snapshot_spec.json

        echo "Single Component mode? ${SINGLE_COMPONENT}"
        if [ "${SINGLE_COMPONENT}" == "true" ]; then

          snapshot_type="$(
            < snapshot.json jq -r '.metadata.labels."test.appstudio.openshift.io/type" // ""'
          )"

          snapshot_component="$(
            < snapshot.json jq -r '.metadata.labels."appstudio.openshift.io/component" // ""'
          )"

          echo "Snapshot type: ${snapshot_type}"
          echo "Snapshot component: ${snapshot_component}"
          if [ "${snapshot_type}" == "component" ] && [ "${snapshot_component}" != "" ]; then
            echo "Single Component mode is ${SINGLE_COMPONENT} and Snapshot type is component"

            jq --arg component "${snapshot_component}" \
            'del(.components[] | select(.name != $component))' snapshot_spec_original.json > snapshot_spec.json

            ## make sure we still have 1 component
            component_count=$(jq -r '[ .components[] ] | length' snapshot_spec.json)
            echo "Component count: ${component_count}"
            if [ "${component_count}" != "1" ] ; then
              echo "Error: Reduced Snapshot has ${component_count} components. It should contain 1"
              echo "       Verify that the Snapshot contains the built component: ${snapshot_component}"
              exit 1
            fi
          fi
        fi
    - name: push-snapshot-to-quay
      image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
      script: |
        #!/usr/bin/env bash
        set -eux

        push_image() { # Expected arguments are [name, containerImage, repository, tag]
          # this task is intended to be used for quay.io
          REGISTRY=quay.io

          SOURCE_AUTH_FILE=$(mktemp)
          SOURCE_REPO=${2%%@sha256:*}
          select-oci-auth "$2" | jq -c \
            '.auths."'"$SOURCE_REPO"'" = .auths."'"$REGISTRY"'" | del(.auths."'"$REGISTRY"'")' > "$SOURCE_AUTH_FILE"

          DEST_AUTH_FILE=$(mktemp)
          # the auth key will be modified to the full repository path, so that
          # we can create a combined auth file with source and destination entries for `cosign copy` later
          select-oci-auth "$3" | jq -c \
            '.auths."'"$3"'" = .auths."'"$REGISTRY"'" | del(.auths."'"$REGISTRY"'")' > "$DEST_AUTH_FILE"

          DESTINATION_DIGEST=$(oras resolve --registry-config "$DEST_AUTH_FILE" "$3:$4" || true)
          ORIGIN_DIGEST=$(oras resolve --registry-config "$SOURCE_AUTH_FILE" "$2")

          if [[ "$DESTINATION_DIGEST" != "$ORIGIN_DIGEST" || -z "$DESTINATION_DIGEST" ]]; then
            # Create a combined auth file to enable partial oci matches to work
            DOCKER_CONFIG="$(mktemp -d)"
            export DOCKER_CONFIG

            # SC2128 - "Expanding an array without an index only gives the element in the index 0."
            # is disabled because "$item" on the next line should only have one element, so there
            # is no need to get any index other than 0.

            # shellcheck disable=SC2128
            jq -s 'reduce .[] as $item ({}; . * $item)' \
              "$SOURCE_AUTH_FILE" "$DEST_AUTH_FILE" > "$DOCKER_CONFIG"/config.json

            if [[ "$(params.skipAttestations)" == "true" ]]; then
                skopeo copy --all "docker://$2" "docker://$3"
            else
                cosign copy -f "$2" "$3:$4"
            fi

            echo "Pushed image $2 to repository $3:$4"
          else
            echo "Component push skipped (source digest exists at destination): $1 $2"
          fi

        }

        SNAPSHOT_SPEC="$(< snapshot_spec.json jq '.')"

        IFS='/' read -r "RP_NAMESPACE" "RP_NAME" <<< "$(params.releasePlan)"
        RP_DATA=$(kubectl get releaseplan "$RP_NAME" -n "$RP_NAMESPACE" \
          -o jsonpath='{.spec.data.mapping}')

        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_SPEC")

        if [[ $NUM_COMPONENTS == 0 ]]; then
          echo "No components in snapshot. There needs to be at least one component" \
            "in the snapshot for this task to run."
          exit 1
        fi

        for ((i = 0; i < NUM_COMPONENTS; i++)); do

          COMPONENT=$(echo -n "$SNAPSHOT_SPEC" | jq -c --argjson i "$i" '.components[$i]')
          NAME=$(jq -r '.name' <<< "$COMPONENT")
          COMPONENT_DESTINATION=$(echo -n "$RP_DATA" | jq -c --arg c "$NAME" '.components[] | select(.name == $c)')

          if [[ "$COMPONENT_DESTINATION" == "" ]]; then
            echo "No mapping for ${NAME}. Skipping."
            continue
          fi

          CONTAINER_IMAGE=$(jq -r '.containerImage' <<< "$COMPONENT")
          REPOSITORY=$(jq -r '.repository' <<< "$COMPONENT_DESTINATION")
          IMAGE_TAGS=$(jq -r '.tags' <<< "$COMPONENT_DESTINATION")

          for TAG in $(jq -r '.[]' <<< "$IMAGE_TAGS"); do
            push_image "$NAME" "$CONTAINER_IMAGE" "$REPOSITORY" "$TAG"
          done

        done
